"""Command line for the famos library.

    python -m famos.cli translate <seq> [-o chain.yaml]   imc sequence -> YAML
    python -m famos.cli show <chain.yaml> [channel ...]    what runs on a channel
    python -m famos.cli licenses [--allow-review]          dependency licence gate
    python -m famos.cli selftest                           chunked == unchunked

Every command is read-only except `translate`, which writes one YAML file and
refuses to overwrite an existing one unless `--force` is given.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np


def _yaml_for(tr, sample_rate_hz=None) -> str:
    """Render a translated chain as YAML, with the source line as a comment."""
    out = [f"# Generated by famos.cli translate -- review before use.",
           f"# Untranslated statements: {len(tr.unmapped)}",
           f"name: {tr.chain.name}"]
    if sample_rate_hz:
        out.append(f"sample_rate_hz: {sample_rate_hz}")
    else:
        out.append("# sample_rate_hz omitted on purpose: it must come from the")
        out.append("# data file header at run time, never from a default here.")
    out.append("channels:")
    for ch in sorted(tr.chain.channels):
        out.append(f"  {ch}:")
        for st in tr.chain.channels[ch]:
            ps = ", ".join(f"{k}: {v}" for k, v in sorted(st.params.items()))
            out.append(f"    - {{op: {st.op}, {ps}}}")
    if tr.chain.final:
        out.append("finally:")
        for st in tr.chain.final:
            ps = ", ".join(f"{k}: {v}" for k, v in sorted(st.params.items()))
            out.append(f"  - {{op: {st.op}, {ps}}}")
    if tr.unmapped:
        out.append("")
        out.append("# NOT TRANSLATED -- these are not preprocessing operators and")
        out.append("# are NOT covered by this chain. Each needs a decision:")
        for u in tr.unmapped:
            out.append(f"#   {u}")
    return "\n".join(out) + "\n"


def cmd_translate(args) -> int:
    from famos.chain import from_seq

    src = Path(args.seq)
    tr = from_seq(src, name=args.name)
    print(tr.report())
    text = _yaml_for(tr, args.sample_rate_hz)
    if args.output:
        dest = Path(args.output)
        if dest.exists() and not args.force:
            print(f"\nrefusing to overwrite {dest} (pass --force)")
            return 1
        dest.write_text(text, encoding="utf-8")
        print(f"\nwritten: {dest}")
    else:
        print("\n" + text)
    return 0


def cmd_show(args) -> int:
    from famos.chain import load_chain

    chain = load_chain(Path(args.chain))
    names = args.channels or sorted(chain.channels)
    print(f"chain: {chain.name}")
    for ch in names:
        stages = chain.stages_for(ch)
        desc = " -> ".join(s.describe() for s in stages) or "(nothing)"
        print(f"  {ch:<22} {desc}")
    return 0


def cmd_licenses(args) -> int:
    from famos.licenses import gate
    return gate(allow_review=args.allow_review)


def cmd_selftest(args) -> int:
    """Prove chunked execution is bit-identical to whole-record execution."""
    from famos import ops
    from famos.chunked import (StreamingFiltLP, StreamingRed, StreamingSmo,
                               chunk_indices)

    fs, n = 1000.0, 60_000
    rng = np.random.default_rng(3)
    t = np.arange(n) / fs
    x = np.cumsum(rng.standard_normal(n)) * 0.01 + 0.18 + 0.5 * np.sin(2*np.pi*3*t)
    ref_l = ops.filtlp(x, 5.0, 4, fs)
    ref_s = ops.smo(ref_l, 0.5, fs)
    ref_r = ops.red(ref_s, 10)

    print(f"record {n:,} samples at {fs:g} Hz; chain FiltLP(4,5) -> smo(0.5) -> red(10)")
    ok = True
    for chunk in (600, 1024, 4096, 7777, 20_000, 59_999):
        f = StreamingFiltLP(5.0, 4, fs)
        parts = [f.process(x[a:b], is_first=first)
                 for a, b, first, _ in chunk_indices(n, chunk)]
        got_l = np.concatenate(parts)
        got_s = np.concatenate(list(StreamingSmo(0.5, fs).run(iter(parts))))
        r = StreamingRed(10)
        got_r = np.concatenate([r.process(got_s[a:b])
                                for a, b, _, _ in chunk_indices(n, chunk)])
        same = (np.array_equal(got_l, ref_l) and np.array_equal(got_s, ref_s)
                and np.array_equal(got_r, ref_r))
        ok &= same
        print(f"  chunk {chunk:>7,}: bit-identical = {same}")
    print("\nPASS" if ok else "\nFAIL - chunking changes the result")
    return 0 if ok else 1


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(prog="famos", description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    t = sub.add_parser("translate", help="imc sequence -> chain YAML")
    t.add_argument("seq")
    t.add_argument("-o", "--output")
    t.add_argument("--name")
    t.add_argument("--sample-rate-hz", type=float, dest="sample_rate_hz")
    t.add_argument("--force", action="store_true")
    t.set_defaults(func=cmd_translate)

    s = sub.add_parser("show", help="what the chain runs on given channels")
    s.add_argument("chain")
    s.add_argument("channels", nargs="*")
    s.set_defaults(func=cmd_show)

    l = sub.add_parser("licenses", help="dependency licence gate")
    l.add_argument("--allow-review", action="store_true")
    l.set_defaults(func=cmd_licenses)

    st = sub.add_parser("selftest", help="chunked == unchunked, bitwise")
    st.set_defaults(func=cmd_selftest)

    args = ap.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
